# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'descripcion.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_descripcion(object):
    def setupUi(self, MainWindow_descripcion):
        MainWindow_descripcion.setObjectName("MainWindow_descripcion")
        MainWindow_descripcion.resize(512, 629)
        self.centralwidget = QtWidgets.QWidget(MainWindow_descripcion)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.dateEdit_descripcion = QtWidgets.QDateEdit(self.splitter)
        self.dateEdit_descripcion.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dateEdit_descripcion.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit_descripcion.setCalendarPopup(True)
        self.dateEdit_descripcion.setDate(QtCore.QDate(2021, 1, 1))
        self.dateEdit_descripcion.setObjectName("dateEdit_descripcion")
        self.Button_buscar = QtWidgets.QPushButton(self.splitter)
        self.Button_buscar.setObjectName("Button_buscar")
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_diaCiclo = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_diaCiclo.setFont(font)
        self.label_diaCiclo.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.label_diaCiclo.setText("")
        self.label_diaCiclo.setObjectName("label_diaCiclo")
        self.horizontalLayout.addWidget(self.label_diaCiclo)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_numeroCiclo = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_numeroCiclo.setFont(font)
        self.label_numeroCiclo.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.label_numeroCiclo.setText("")
        self.label_numeroCiclo.setObjectName("label_numeroCiclo")
        self.horizontalLayout.addWidget(self.label_numeroCiclo)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_faseCiclo = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_faseCiclo.setFont(font)
        self.label_faseCiclo.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.label_faseCiclo.setText("")
        self.label_faseCiclo.setObjectName("label_faseCiclo")
        self.horizontalLayout_2.addWidget(self.label_faseCiclo)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_faseLunar = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_faseLunar.setFont(font)
        self.label_faseLunar.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.label_faseLunar.setText("")
        self.label_faseLunar.setObjectName("label_faseLunar")
        self.horizontalLayout_2.addWidget(self.label_faseLunar)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_tipoSangrad = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_tipoSangrad.setFont(font)
        self.label_tipoSangrad.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.label_tipoSangrad.setText("")
        self.label_tipoSangrad.setObjectName("label_tipoSangrad")
        self.horizontalLayout_3.addWidget(self.label_tipoSangrad)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_tipoFlujo = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_tipoFlujo.setFont(font)
        self.label_tipoFlujo.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.label_tipoFlujo.setText("")
        self.label_tipoFlujo.setObjectName("label_tipoFlujo")
        self.horizontalLayout_3.addWidget(self.label_tipoFlujo)
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_sensacEnergia = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_sensacEnergia.setFont(font)
        self.label_sensacEnergia.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.label_sensacEnergia.setText("")
        self.label_sensacEnergia.setObjectName("label_sensacEnergia")
        self.horizontalLayout_4.addWidget(self.label_sensacEnergia)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.label_sensacVulvar = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_sensacVulvar.setFont(font)
        self.label_sensacVulvar.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.label_sensacVulvar.setText("")
        self.label_sensacVulvar.setObjectName("label_sensacVulvar")
        self.horizontalLayout_4.addWidget(self.label_sensacVulvar)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_heces = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_heces.setFont(font)
        self.label_heces.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.label_heces.setText("")
        self.label_heces.setObjectName("label_heces")
        self.horizontalLayout_5.addWidget(self.label_heces)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.label_sueno = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_sueno.setFont(font)
        self.label_sueno.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.label_sueno.setText("")
        self.label_sueno.setObjectName("label_sueno")
        self.horizontalLayout_5.addWidget(self.label_sueno)
        self.gridLayout.addLayout(self.horizontalLayout_5, 5, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_ayuno = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_ayuno.setFont(font)
        self.label_ayuno.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.label_ayuno.setText("")
        self.label_ayuno.setObjectName("label_ayuno")
        self.horizontalLayout_6.addWidget(self.label_ayuno)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.label_relacionSexuales = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_relacionSexuales.setFont(font)
        self.label_relacionSexuales.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.label_relacionSexuales.setText("")
        self.label_relacionSexuales.setObjectName("label_relacionSexuales")
        self.horizontalLayout_6.addWidget(self.label_relacionSexuales)
        self.gridLayout.addLayout(self.horizontalLayout_6, 6, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_carbohidratos = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_carbohidratos.setFont(font)
        self.label_carbohidratos.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.label_carbohidratos.setText("")
        self.label_carbohidratos.setObjectName("label_carbohidratos")
        self.horizontalLayout_7.addWidget(self.label_carbohidratos)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.label_ejercicioFuerza = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_ejercicioFuerza.setFont(font)
        self.label_ejercicioFuerza.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.label_ejercicioFuerza.setText("")
        self.label_ejercicioFuerza.setObjectName("label_ejercicioFuerza")
        self.horizontalLayout_7.addWidget(self.label_ejercicioFuerza)
        self.gridLayout.addLayout(self.horizontalLayout_7, 7, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_ejercicioCardio = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_ejercicioCardio.setFont(font)
        self.label_ejercicioCardio.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.label_ejercicioCardio.setText("")
        self.label_ejercicioCardio.setObjectName("label_ejercicioCardio")
        self.horizontalLayout_8.addWidget(self.label_ejercicioCardio)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.label_irritable = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_irritable.setFont(font)
        self.label_irritable.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.label_irritable.setText("")
        self.label_irritable.setObjectName("label_irritable")
        self.horizontalLayout_8.addWidget(self.label_irritable)
        self.gridLayout.addLayout(self.horizontalLayout_8, 8, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_atencionConc = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_atencionConc.setFont(font)
        self.label_atencionConc.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.label_atencionConc.setText("")
        self.label_atencionConc.setObjectName("label_atencionConc")
        self.horizontalLayout_9.addWidget(self.label_atencionConc)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.label_sensible = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_sensible.setFont(font)
        self.label_sensible.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.label_sensible.setText("")
        self.label_sensible.setObjectName("label_sensible")
        self.horizontalLayout_9.addWidget(self.label_sensible)
        self.gridLayout.addLayout(self.horizontalLayout_9, 9, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_triste = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_triste.setFont(font)
        self.label_triste.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.label_triste.setText("")
        self.label_triste.setObjectName("label_triste")
        self.horizontalLayout_10.addWidget(self.label_triste)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem9)
        self.label_alegre = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_alegre.setFont(font)
        self.label_alegre.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.label_alegre.setText("")
        self.label_alegre.setObjectName("label_alegre")
        self.horizontalLayout_10.addWidget(self.label_alegre)
        self.gridLayout.addLayout(self.horizontalLayout_10, 10, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_tranquila = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_tranquila.setFont(font)
        self.label_tranquila.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.label_tranquila.setText("")
        self.label_tranquila.setObjectName("label_tranquila")
        self.horizontalLayout_11.addWidget(self.label_tranquila)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem10)
        self.label_tensionada = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_tensionada.setFont(font)
        self.label_tensionada.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.label_tensionada.setText("")
        self.label_tensionada.setObjectName("label_tensionada")
        self.horizontalLayout_11.addWidget(self.label_tensionada)
        self.gridLayout.addLayout(self.horizontalLayout_11, 11, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_hinchazon = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_hinchazon.setFont(font)
        self.label_hinchazon.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.label_hinchazon.setText("")
        self.label_hinchazon.setObjectName("label_hinchazon")
        self.horizontalLayout_12.addWidget(self.label_hinchazon)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem11)
        self.label_acne = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_acne.setFont(font)
        self.label_acne.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.label_acne.setText("")
        self.label_acne.setObjectName("label_acne")
        self.horizontalLayout_12.addWidget(self.label_acne)
        self.gridLayout.addLayout(self.horizontalLayout_12, 12, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_dolorOvarios = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_dolorOvarios.setFont(font)
        self.label_dolorOvarios.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.label_dolorOvarios.setText("")
        self.label_dolorOvarios.setObjectName("label_dolorOvarios")
        self.horizontalLayout_13.addWidget(self.label_dolorOvarios)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem12)
        self.label_dolorLumbar = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_dolorLumbar.setFont(font)
        self.label_dolorLumbar.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.label_dolorLumbar.setText("")
        self.label_dolorLumbar.setObjectName("label_dolorLumbar")
        self.horizontalLayout_13.addWidget(self.label_dolorLumbar)
        self.gridLayout.addLayout(self.horizontalLayout_13, 13, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_cansancio = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_cansancio.setFont(font)
        self.label_cansancio.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.label_cansancio.setText("")
        self.label_cansancio.setObjectName("label_cansancio")
        self.horizontalLayout_14.addWidget(self.label_cansancio)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem13)
        self.label_pechoSensible = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_pechoSensible.setFont(font)
        self.label_pechoSensible.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.label_pechoSensible.setText("")
        self.label_pechoSensible.setObjectName("label_pechoSensible")
        self.horizontalLayout_14.addWidget(self.label_pechoSensible)
        self.gridLayout.addLayout(self.horizontalLayout_14, 14, 0, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_antojos = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_antojos.setFont(font)
        self.label_antojos.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.label_antojos.setText("")
        self.label_antojos.setObjectName("label_antojos")
        self.horizontalLayout_15.addWidget(self.label_antojos)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem14)
        self.label_deseoSexual = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_deseoSexual.setFont(font)
        self.label_deseoSexual.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.label_deseoSexual.setText("")
        self.label_deseoSexual.setObjectName("label_deseoSexual")
        self.horizontalLayout_15.addWidget(self.label_deseoSexual)
        self.gridLayout.addLayout(self.horizontalLayout_15, 15, 0, 1, 1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_notasEmocionales = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_notasEmocionales.setFont(font)
        self.label_notasEmocionales.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.label_notasEmocionales.setText("")
        self.label_notasEmocionales.setObjectName("label_notasEmocionales")
        self.horizontalLayout_17.addWidget(self.label_notasEmocionales)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem15)
        self.label_notasAlimentacion = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_notasAlimentacion.setFont(font)
        self.label_notasAlimentacion.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.label_notasAlimentacion.setText("")
        self.label_notasAlimentacion.setObjectName("label_notasAlimentacion")
        self.horizontalLayout_17.addWidget(self.label_notasAlimentacion)
        self.gridLayout.addLayout(self.horizontalLayout_17, 16, 0, 1, 1)
        MainWindow_descripcion.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow_descripcion)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_descripcion)

    def retranslateUi(self, MainWindow_descripcion):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_descripcion.setWindowTitle(_translate("MainWindow_descripcion", "Descripción"))
        self.dateEdit_descripcion.setDisplayFormat(_translate("MainWindow_descripcion", "d/MM/yyyy"))
        self.Button_buscar.setText(_translate("MainWindow_descripcion", "Buscar"))
