# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formularioInicial.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main_menstGUI(object):
    def setupUi(self, Main_menstGUI):
        Main_menstGUI.setObjectName("Main_menstGUI")
        Main_menstGUI.resize(808, 631)
        self.centralwidget = QtWidgets.QWidget(Main_menstGUI)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.Button_guardar_main = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Button_guardar_main.setFont(font)
        self.Button_guardar_main.setObjectName("Button_guardar_main")
        self.gridLayout.addWidget(self.Button_guardar_main, 1, 0, 1, 1)
        self.tabWidget_inicio = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_inicio.setObjectName("tabWidget_inicio")
        self.tab_general = QtWidgets.QWidget()
        self.tab_general.setObjectName("tab_general")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_general)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.tab_general)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.dateEdit_fecha = QtWidgets.QDateEdit(self.tab_general)
        self.dateEdit_fecha.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit_fecha.setKeyboardTracking(True)
        self.dateEdit_fecha.setCalendarPopup(True)
        self.dateEdit_fecha.setDate(QtCore.QDate(2021, 1, 1))
        self.dateEdit_fecha.setObjectName("dateEdit_fecha")
        self.horizontalLayout_2.addWidget(self.dateEdit_fecha)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.tab_general)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBox_diaCiclo = QtWidgets.QSpinBox(self.tab_general)
        self.spinBox_diaCiclo.setMinimum(1)
        self.spinBox_diaCiclo.setProperty("value", 1)
        self.spinBox_diaCiclo.setDisplayIntegerBase(10)
        self.spinBox_diaCiclo.setObjectName("spinBox_diaCiclo")
        self.horizontalLayout_2.addWidget(self.spinBox_diaCiclo)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.tab_general)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.spinBox_numCiclo = QtWidgets.QSpinBox(self.tab_general)
        self.spinBox_numCiclo.setMinimum(1)
        self.spinBox_numCiclo.setObjectName("spinBox_numCiclo")
        self.horizontalLayout_2.addWidget(self.spinBox_numCiclo)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.tab_general)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.comboBox_faciclo = QtWidgets.QComboBox(self.tab_general)
        self.comboBox_faciclo.setObjectName("comboBox_faciclo")
        self.comboBox_faciclo.addItem("")
        self.comboBox_faciclo.setItemText(0, "")
        self.comboBox_faciclo.addItem("")
        self.comboBox_faciclo.addItem("")
        self.comboBox_faciclo.addItem("")
        self.comboBox_faciclo.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_faciclo)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.label_7 = QtWidgets.QLabel(self.tab_general)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.comboBox_falunar = QtWidgets.QComboBox(self.tab_general)
        self.comboBox_falunar.setObjectName("comboBox_falunar")
        self.comboBox_falunar.addItem("")
        self.comboBox_falunar.setItemText(0, "")
        self.comboBox_falunar.addItem("")
        self.comboBox_falunar.addItem("")
        self.comboBox_falunar.addItem("")
        self.comboBox_falunar.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_falunar)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.tab_general)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.text_alimentacion = QtWidgets.QTextEdit(self.tab_general)
        self.text_alimentacion.setObjectName("text_alimentacion")
        self.verticalLayout_3.addWidget(self.text_alimentacion)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.tab_general)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.text_emociones = QtWidgets.QTextEdit(self.tab_general)
        self.text_emociones.setObjectName("text_emociones")
        self.verticalLayout.addWidget(self.text_emociones)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.tabWidget_inicio.addTab(self.tab_general, "")
        self.tab_sintomas = QtWidgets.QWidget()
        self.tab_sintomas.setObjectName("tab_sintomas")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_sintomas)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.tab_sintomas)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.groupBox.setFont(font)
        self.groupBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.checkBox_psensible = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_psensible.setObjectName("checkBox_psensible")
        self.gridLayout_5.addWidget(self.checkBox_psensible, 5, 0, 1, 1)
        self.comboBox_tsangrado = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_tsangrado.setObjectName("comboBox_tsangrado")
        self.comboBox_tsangrado.addItem("")
        self.comboBox_tsangrado.setItemText(0, "")
        self.comboBox_tsangrado.addItem("")
        self.comboBox_tsangrado.addItem("")
        self.comboBox_tsangrado.addItem("")
        self.comboBox_tsangrado.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_tsangrado, 0, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 0, 1, 1, 1)
        self.checkBox_deseoSexual = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_deseoSexual.setObjectName("checkBox_deseoSexual")
        self.gridLayout_5.addWidget(self.checkBox_deseoSexual, 7, 0, 1, 1)
        self.comboBox_tflujo = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_tflujo.setObjectName("comboBox_tflujo")
        self.comboBox_tflujo.addItem("")
        self.comboBox_tflujo.setItemText(0, "")
        self.comboBox_tflujo.addItem("")
        self.comboBox_tflujo.addItem("")
        self.comboBox_tflujo.addItem("")
        self.comboBox_tflujo.addItem("")
        self.comboBox_tflujo.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_tflujo, 1, 2, 1, 1)
        self.checkBox_cansancio = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_cansancio.setObjectName("checkBox_cansancio")
        self.gridLayout_5.addWidget(self.checkBox_cansancio, 4, 0, 1, 1)
        self.checkBox_dolumbar = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_dolumbar.setObjectName("checkBox_dolumbar")
        self.gridLayout_5.addWidget(self.checkBox_dolumbar, 3, 0, 1, 1)
        self.checkBox_dolovarios = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_dolovarios.setObjectName("checkBox_dolovarios")
        self.gridLayout_5.addWidget(self.checkBox_dolovarios, 2, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 3, 1, 1, 1)
        self.checkBox_acne = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_acne.setObjectName("checkBox_acne")
        self.gridLayout_5.addWidget(self.checkBox_acne, 1, 0, 1, 1)
        self.checkBox_hinchazon = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_hinchazon.setObjectName("checkBox_hinchazon")
        self.gridLayout_5.addWidget(self.checkBox_hinchazon, 0, 0, 1, 1)
        self.checkBox_antojos = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_antojos.setObjectName("checkBox_antojos")
        self.gridLayout_5.addWidget(self.checkBox_antojos, 6, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 1, 1, 1, 1)
        self.comboBox_sensEnergia = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_sensEnergia.setObjectName("comboBox_sensEnergia")
        self.comboBox_sensEnergia.addItem("")
        self.comboBox_sensEnergia.setItemText(0, "")
        self.comboBox_sensEnergia.addItem("")
        self.comboBox_sensEnergia.addItem("")
        self.comboBox_sensEnergia.addItem("")
        self.comboBox_sensEnergia.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_sensEnergia, 2, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 2, 1, 1, 1)
        self.comboBox_sensVulvar = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_sensVulvar.setObjectName("comboBox_sensVulvar")
        self.comboBox_sensVulvar.addItem("")
        self.comboBox_sensVulvar.setItemText(0, "")
        self.comboBox_sensVulvar.addItem("")
        self.comboBox_sensVulvar.addItem("")
        self.comboBox_sensVulvar.addItem("")
        self.comboBox_sensVulvar.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_sensVulvar, 3, 2, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_sintomas)
        self.groupBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_irritable = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_irritable.setObjectName("checkBox_irritable")
        self.verticalLayout_2.addWidget(self.checkBox_irritable)
        self.checkBox_atenConcent = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_atenConcent.setObjectName("checkBox_atenConcent")
        self.verticalLayout_2.addWidget(self.checkBox_atenConcent)
        self.checkBox_sensible = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_sensible.setObjectName("checkBox_sensible")
        self.verticalLayout_2.addWidget(self.checkBox_sensible)
        self.checkBox_triste = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_triste.setObjectName("checkBox_triste")
        self.verticalLayout_2.addWidget(self.checkBox_triste)
        self.checkBox_alegre = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_alegre.setObjectName("checkBox_alegre")
        self.verticalLayout_2.addWidget(self.checkBox_alegre)
        self.checkBox_tranquila = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_tranquila.setObjectName("checkBox_tranquila")
        self.verticalLayout_2.addWidget(self.checkBox_tranquila)
        self.checkBox_tensionada = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_tensionada.setObjectName("checkBox_tensionada")
        self.verticalLayout_2.addWidget(self.checkBox_tensionada)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.tabWidget_inicio.addTab(self.tab_sintomas, "")
        self.tab_habitos = QtWidgets.QWidget()
        self.tab_habitos.setObjectName("tab_habitos")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_habitos)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line_sueno = QtWidgets.QLineEdit(self.tab_habitos)
        self.line_sueno.setObjectName("line_sueno")
        self.gridLayout_2.addWidget(self.line_sueno, 2, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_habitos)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 3, 0, 1, 1)
        self.comboBox_carbohidratos = QtWidgets.QComboBox(self.tab_habitos)
        self.comboBox_carbohidratos.setObjectName("comboBox_carbohidratos")
        self.comboBox_carbohidratos.addItem("")
        self.comboBox_carbohidratos.setItemText(0, "")
        self.comboBox_carbohidratos.addItem("")
        self.comboBox_carbohidratos.addItem("")
        self.comboBox_carbohidratos.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_carbohidratos, 5, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab_habitos)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_habitos)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 1, 0, 1, 1)
        self.line_heces = QtWidgets.QLineEdit(self.tab_habitos)
        self.line_heces.setInputMask("")
        self.line_heces.setObjectName("line_heces")
        self.gridLayout_2.addWidget(self.line_heces, 1, 1, 1, 1)
        self.doubleSpinBox_temperatura = QtWidgets.QDoubleSpinBox(self.tab_habitos)
        self.doubleSpinBox_temperatura.setEnabled(True)
        self.doubleSpinBox_temperatura.setWrapping(False)
        self.doubleSpinBox_temperatura.setFrame(True)
        self.doubleSpinBox_temperatura.setReadOnly(False)
        self.doubleSpinBox_temperatura.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.doubleSpinBox_temperatura.setAccelerated(False)
        self.doubleSpinBox_temperatura.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.doubleSpinBox_temperatura.setKeyboardTracking(False)
        self.doubleSpinBox_temperatura.setProperty("showGroupSeparator", False)
        self.doubleSpinBox_temperatura.setPrefix("")
        self.doubleSpinBox_temperatura.setSuffix("")
        self.doubleSpinBox_temperatura.setDecimals(2)
        self.doubleSpinBox_temperatura.setMinimum(30.0)
        self.doubleSpinBox_temperatura.setMaximum(46.99)
        self.doubleSpinBox_temperatura.setSingleStep(0.1)
        self.doubleSpinBox_temperatura.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.doubleSpinBox_temperatura.setProperty("value", 36.0)
        self.doubleSpinBox_temperatura.setObjectName("doubleSpinBox_temperatura")
        self.gridLayout_2.addWidget(self.doubleSpinBox_temperatura, 0, 1, 1, 1)
        self.checkBox_relaSexual = QtWidgets.QCheckBox(self.tab_habitos)
        self.checkBox_relaSexual.setObjectName("checkBox_relaSexual")
        self.gridLayout_2.addWidget(self.checkBox_relaSexual, 4, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_habitos)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 2, 0, 1, 1)
        self.line_ayuno = QtWidgets.QLineEdit(self.tab_habitos)
        self.line_ayuno.setObjectName("line_ayuno")
        self.gridLayout_2.addWidget(self.line_ayuno, 3, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_habitos)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 5, 0, 1, 1)
        self.groupBox_ejercicio = QtWidgets.QGroupBox(self.tab_habitos)
        self.groupBox_ejercicio.setCheckable(True)
        self.groupBox_ejercicio.setChecked(False)
        self.groupBox_ejercicio.setObjectName("groupBox_ejercicio")
        self.label_21 = QtWidgets.QLabel(self.groupBox_ejercicio)
        self.label_21.setGeometry(QtCore.QRect(12, 32, 129, 17))
        self.label_21.setObjectName("label_21")
        self.comboBox_ejerFuerza = QtWidgets.QComboBox(self.groupBox_ejercicio)
        self.comboBox_ejerFuerza.setGeometry(QtCore.QRect(147, 32, 122, 25))
        self.comboBox_ejerFuerza.setObjectName("comboBox_ejerFuerza")
        self.comboBox_ejerFuerza.addItem("")
        self.comboBox_ejerFuerza.addItem("")
        self.comboBox_ejerFuerza.addItem("")
        self.label_22 = QtWidgets.QLabel(self.groupBox_ejercicio)
        self.label_22.setGeometry(QtCore.QRect(12, 63, 127, 17))
        self.label_22.setObjectName("label_22")
        self.comboBox_ejerCardio = QtWidgets.QComboBox(self.groupBox_ejercicio)
        self.comboBox_ejerCardio.setGeometry(QtCore.QRect(147, 63, 111, 25))
        self.comboBox_ejerCardio.setObjectName("comboBox_ejerCardio")
        self.comboBox_ejerCardio.addItem("")
        self.comboBox_ejerCardio.addItem("")
        self.comboBox_ejerCardio.addItem("")
        self.comboBox_ejerCardio.addItem("")
        self.gridLayout_2.addWidget(self.groupBox_ejercicio, 6, 0, 1, 2)
        self.Button_grafica = QtWidgets.QPushButton(self.tab_habitos)
        self.Button_grafica.setObjectName("Button_grafica")
        self.gridLayout_2.addWidget(self.Button_grafica, 7, 0, 1, 2)
        self.tabWidget_inicio.addTab(self.tab_habitos, "")
        self.gridLayout.addWidget(self.tabWidget_inicio, 0, 0, 1, 2)
        self.Button_editar = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Button_editar.setFont(font)
        self.Button_editar.setObjectName("Button_editar")
        self.gridLayout.addWidget(self.Button_editar, 1, 1, 1, 1)
        Main_menstGUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(Main_menstGUI)
        self.tabWidget_inicio.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Main_menstGUI)

    def retranslateUi(self, Main_menstGUI):
        _translate = QtCore.QCoreApplication.translate
        Main_menstGUI.setWindowTitle(_translate("Main_menstGUI", "mentsGUI"))
        self.Button_guardar_main.setText(_translate("Main_menstGUI", "Guardar"))
        self.label_3.setText(_translate("Main_menstGUI", "Fecha:"))
        self.dateEdit_fecha.setDisplayFormat(_translate("Main_menstGUI", "d/MM/yyyy"))
        self.label_2.setText(_translate("Main_menstGUI", "Día del ciclo:"))
        self.label.setText(_translate("Main_menstGUI", "Número del ciclo:"))
        self.label_6.setText(_translate("Main_menstGUI", "Fase de ciclo:"))
        self.comboBox_faciclo.setItemText(1, _translate("Main_menstGUI", "Menstrual"))
        self.comboBox_faciclo.setItemText(2, _translate("Main_menstGUI", "Folicular"))
        self.comboBox_faciclo.setItemText(3, _translate("Main_menstGUI", "Ovulatoria"))
        self.comboBox_faciclo.setItemText(4, _translate("Main_menstGUI", "Lútea"))
        self.label_7.setText(_translate("Main_menstGUI", "Fase lunar:"))
        self.comboBox_falunar.setItemText(1, _translate("Main_menstGUI", "Menguante"))
        self.comboBox_falunar.setItemText(2, _translate("Main_menstGUI", "Luna nueva"))
        self.comboBox_falunar.setItemText(3, _translate("Main_menstGUI", "Creciente"))
        self.comboBox_falunar.setItemText(4, _translate("Main_menstGUI", "Luna llena"))
        self.label_5.setText(_translate("Main_menstGUI", "Notas alimentación:"))
        self.label_4.setText(_translate("Main_menstGUI", "Notas emocionales:"))
        self.tabWidget_inicio.setTabText(self.tabWidget_inicio.indexOf(self.tab_general), _translate("Main_menstGUI", "General"))
        self.groupBox.setTitle(_translate("Main_menstGUI", "Síntomas físicos"))
        self.checkBox_psensible.setText(_translate("Main_menstGUI", "Pecho sensible"))
        self.comboBox_tsangrado.setItemText(1, _translate("Main_menstGUI", "Ninguno"))
        self.comboBox_tsangrado.setItemText(2, _translate("Main_menstGUI", "Poco"))
        self.comboBox_tsangrado.setItemText(3, _translate("Main_menstGUI", "Normal"))
        self.comboBox_tsangrado.setItemText(4, _translate("Main_menstGUI", "Mucho"))
        self.label_12.setText(_translate("Main_menstGUI", "Tipo sangrado:"))
        self.checkBox_deseoSexual.setText(_translate("Main_menstGUI", "Deseo sexual"))
        self.comboBox_tflujo.setItemText(1, _translate("Main_menstGUI", "Ninguno"))
        self.comboBox_tflujo.setItemText(2, _translate("Main_menstGUI", "Seco"))
        self.comboBox_tflujo.setItemText(3, _translate("Main_menstGUI", "Acuoso"))
        self.comboBox_tflujo.setItemText(4, _translate("Main_menstGUI", "Cremoso"))
        self.comboBox_tflujo.setItemText(5, _translate("Main_menstGUI", "Clara de huevo"))
        self.checkBox_cansancio.setText(_translate("Main_menstGUI", "Cansancio"))
        self.checkBox_dolumbar.setText(_translate("Main_menstGUI", "Dolor lumbar"))
        self.checkBox_dolovarios.setText(_translate("Main_menstGUI", "Dolor ovarios"))
        self.label_13.setText(_translate("Main_menstGUI", "Sensación vulvar:"))
        self.checkBox_acne.setText(_translate("Main_menstGUI", "Acné"))
        self.checkBox_hinchazon.setText(_translate("Main_menstGUI", "Hinchazón"))
        self.checkBox_antojos.setText(_translate("Main_menstGUI", "Antojos"))
        self.label_14.setText(_translate("Main_menstGUI", "Tipo de flujo:"))
        self.comboBox_sensEnergia.setItemText(1, _translate("Main_menstGUI", "Ninguno"))
        self.comboBox_sensEnergia.setItemText(2, _translate("Main_menstGUI", "Alta"))
        self.comboBox_sensEnergia.setItemText(3, _translate("Main_menstGUI", "Normal"))
        self.comboBox_sensEnergia.setItemText(4, _translate("Main_menstGUI", "Baja"))
        self.label_15.setText(_translate("Main_menstGUI", "Sensación de energía:"))
        self.comboBox_sensVulvar.setItemText(1, _translate("Main_menstGUI", "Ninguno"))
        self.comboBox_sensVulvar.setItemText(2, _translate("Main_menstGUI", "Húmeda"))
        self.comboBox_sensVulvar.setItemText(3, _translate("Main_menstGUI", "Seca"))
        self.comboBox_sensVulvar.setItemText(4, _translate("Main_menstGUI", "Anormal"))
        self.groupBox_2.setTitle(_translate("Main_menstGUI", "Síntomas emocionales"))
        self.checkBox_irritable.setText(_translate("Main_menstGUI", "Irritable"))
        self.checkBox_atenConcent.setText(_translate("Main_menstGUI", "Atención y concentración"))
        self.checkBox_sensible.setText(_translate("Main_menstGUI", "Sensible"))
        self.checkBox_triste.setText(_translate("Main_menstGUI", "Triste"))
        self.checkBox_alegre.setText(_translate("Main_menstGUI", "Alegre"))
        self.checkBox_tranquila.setText(_translate("Main_menstGUI", "Tranquila"))
        self.checkBox_tensionada.setText(_translate("Main_menstGUI", "Tensionada"))
        self.tabWidget_inicio.setTabText(self.tabWidget_inicio.indexOf(self.tab_sintomas), _translate("Main_menstGUI", "Síntomas"))
        self.label_19.setText(_translate("Main_menstGUI", "Ayuno (horas):"))
        self.comboBox_carbohidratos.setItemText(1, _translate("Main_menstGUI", "Alto (>80g)"))
        self.comboBox_carbohidratos.setItemText(2, _translate("Main_menstGUI", "Moderado (40g - 80g)"))
        self.comboBox_carbohidratos.setItemText(3, _translate("Main_menstGUI", "Bajo (<40g)"))
        self.label_16.setText(_translate("Main_menstGUI", "Temperatura:"))
        self.label_17.setText(_translate("Main_menstGUI", "Heces:"))
        self.checkBox_relaSexual.setText(_translate("Main_menstGUI", "Relaciones sexuales"))
        self.label_18.setText(_translate("Main_menstGUI", "Sueño (horas):"))
        self.label_20.setText(_translate("Main_menstGUI", "Carbohidratos:"))
        self.groupBox_ejercicio.setTitle(_translate("Main_menstGUI", "Ejercicio"))
        self.label_21.setText(_translate("Main_menstGUI", "Ejercicio de fuerza:"))
        self.comboBox_ejerFuerza.setItemText(0, _translate("Main_menstGUI", "No "))
        self.comboBox_ejerFuerza.setItemText(1, _translate("Main_menstGUI", "Tren superior"))
        self.comboBox_ejerFuerza.setItemText(2, _translate("Main_menstGUI", "Tren inferior"))
        self.label_22.setText(_translate("Main_menstGUI", "Ejercicio de cardio:"))
        self.comboBox_ejerCardio.setItemText(0, _translate("Main_menstGUI", "No"))
        self.comboBox_ejerCardio.setItemText(1, _translate("Main_menstGUI", "Cardio"))
        self.comboBox_ejerCardio.setItemText(2, _translate("Main_menstGUI", "Cardio hit"))
        self.comboBox_ejerCardio.setItemText(3, _translate("Main_menstGUI", "Senderismo"))
        self.Button_grafica.setText(_translate("Main_menstGUI", "Ver gráfica"))
        self.tabWidget_inicio.setTabText(self.tabWidget_inicio.indexOf(self.tab_habitos), _translate("Main_menstGUI", "Hábitos"))
        self.Button_editar.setText(_translate("Main_menstGUI", "Editar"))
